---
eureka:
    instance:
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        statusPageUrlPath: ${management.contextPath}/info
        healthCheckUrlPath: ${management.contextPath}/health
        hostname: localhost

---
spring:
    profiles: primary
server:
    port: 8010
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8011/eureka/ 

---
spring:
    profiles: secondary
server:
    port: 8011
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka/


