---
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka/, http://localhost:8011/eureka/ 

---
spring:
    profiles: primary
server:
    port: 8010

---
spring:
    profiles: secondary
server:
    port: 8011
